language: node_js
node_js:
- '0.12'
- '0.11'
- '0.10'
- iojs
- iojs-v1.0.4
before_script:
- npm install -g grunt-cli
deploy:
  provider: npm
  email: jeanpylone@gmail.com
  api_key:
    secure: KKeL+p8bbSwr/LiJbFhziGqaPRZbnpEEZIaZJy5fsHWJBrGAZqz50+BacEOFfZKMewFjJ0cUUeOTSLIw1MmBhCEyxRBalCrmoFDYBTtZcfYbRmzbbS/OVWuwY6YHswHw/gp66BNWDIN711HOWnhV/8UBTZ+s0Psb3ZrsRxlseP/mPZIthrxPMsFXjkcMfI0N79PQDVWVcM6meTmqGgIMtQK8bW4JUEwyWOx+d4CB4vAU99boB81Q0WQQyLX0gQWFlrEw6iUHIpcIPNoyJmz8zGa2vPsYYxdEIKPgDlExoFSdTkMoRCdZSL8YeSH3I4cQO1YKNNp3nI5n/7XZCApe17vNH9WDp9BF/Vb8xEmtJv3mkemWas7rOMQH0l4d+HOAh0bnRjuT492lBnerz05A96WXNlByGxfLwiuKU1ABxbbWk97eC/rOfMyOIdKC1F6R27wUNsxUGnrdIECefGqTCWpt2TbsddoDoKwBnzhfDvfVpYRDUfa7ykEP588si5gU+w9aG3aWCcHg5xg340OL7UShGELMTqT1GhkT/9hq20/esYCOdqo1+1Bi31cbpl4i3XtJG1HyEVrnJCdQse9F2Y9586u1nGbrbX9ZRNpiXWXkRaCH1BPCIZ1N2nYyyokL8/VJ9CS3WBCn4Jna+n9TMEdEPsoO7P6Oe+znQUzXhiw=
  on:
    node: '0.12'
    tags: true
    repo: jeanpylone/throu.js
